# Generated by Django 3.1.3 on 2020-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('close', 'CLOSE')], default='open', max_length=6)),
                ('giveaways_category', models.CharField(choices=[('other', 'Other'), ('mobile', 'Mobile'), ('technology', 'Technology'), ('electronic', 'Electronic'), ('gaming', 'Gaming'), ('how_to', 'Howto'), ('sports', 'Sports'), ('software', 'Software'), ('hardware', 'Hardware'), ('coupan', 'Coupan'), ('quiz', 'Quiz'), ('education', 'Education')], default='other', max_length=60)),
                ('product_name', models.CharField(max_length=100)),
                ('unit', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=1000)),
                ('links', models.URLField()),
            ],
        ),
    ]
