# Generated by Django 3.1.3 on 2020-12-26 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_giveaways'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaways',
            name='winner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
