# Generated by Django 3.1.3 on 2021-03-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_giveaways_winner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaways',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='giveaways',
            name='start_date',
            field=models.DateField(),
        ),
    ]
